/* Generated by Yosys 0.33+6 (git sha1 41b34a193, x86_64-conda-linux-gnu-cc 11.2.0 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/root/conda-eda/conda-eda/workdir/conda-env/conda-bld/yosys_1694128612374/work=/usr/local/src/conda/yosys-0.33_7_g41b34a193 -fdebug-prefix-map=/home/leonardo/miniconda3/envs/digital=/usr/local/src/conda-prefix -fPIC -Os -fno-merge-constants) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "dpram.v:5.1-55.10" *)
module dpram(clk_a, en_a, adr_a, dat_a, we_a, clk_b, en_b, re_b, adr_b, dat_b, dat_a_out);
  (* src = "dpram.v:13.30-13.35" *)
  input [12:0] adr_a;
  wire [12:0] adr_a;
  (* src = "dpram.v:20.30-20.35" *)
  input [12:0] adr_b;
  wire [12:0] adr_b;
  (* src = "dpram.v:11.30-11.35" *)
  input clk_a;
  wire clk_a;
  (* src = "dpram.v:17.30-17.35" *)
  input clk_b;
  wire clk_b;
  (* src = "dpram.v:14.29-14.34" *)
  input [15:0] dat_a;
  wire [15:0] dat_a;
  (* src = "dpram.v:22.30-22.39" *)
  output [15:0] dat_a_out;
  wire [15:0] dat_a_out;
  (* src = "dpram.v:21.30-21.35" *)
  output [15:0] dat_b;
  wire [15:0] dat_b;
  (* src = "dpram.v:12.30-12.34" *)
  input en_a;
  wire en_a;
  (* force_downto = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/techmap.v:614.34-614.35" *)
  wire [1:0] en_a_SB_LUT4_I1_O;
  (* src = "dpram.v:18.30-18.34" *)
  input en_b;
  wire en_b;
  wire en_b_SB_LUT4_I2_O;
  (* force_downto = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \ram.0.0_RDATA ;
  (* force_downto = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \ram.0.0_RDATA_1 ;
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:22.13-22.18" *)
  (* unused_bits = "0 1 2 4 5 6 7 8 9 10 12 13 14 15" *)
  wire [15:0] \ram.0.0_RDATA_2 ;
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:22.13-22.18" *)
  (* unused_bits = "0 1 2 4 5 6 7 8 9 10 12 13 14 15" *)
  wire [15:0] \ram.0.10_RDATA ;
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:22.13-22.18" *)
  (* unused_bits = "0 1 2 4 5 6 7 8 9 10 12 13 14 15" *)
  wire [15:0] \ram.0.11_RDATA ;
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:22.13-22.18" *)
  (* unused_bits = "0 1 2 4 5 6 7 8 9 10 12 13 14 15" *)
  wire [15:0] \ram.0.12_RDATA ;
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:22.13-22.18" *)
  (* unused_bits = "0 1 2 4 5 6 7 8 9 10 12 13 14 15" *)
  wire [15:0] \ram.0.13_RDATA ;
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:22.13-22.18" *)
  (* unused_bits = "0 1 2 4 5 6 7 8 9 10 12 13 14 15" *)
  wire [15:0] \ram.0.14_RDATA ;
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:22.13-22.18" *)
  (* unused_bits = "0 1 2 4 5 6 7 8 9 10 12 13 14 15" *)
  wire [15:0] \ram.0.15_RDATA ;
  (* force_downto = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \ram.0.1_RDATA ;
  (* force_downto = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \ram.0.1_RDATA_1 ;
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:22.13-22.18" *)
  (* unused_bits = "0 1 2 4 5 6 7 8 9 10 12 13 14 15" *)
  wire [15:0] \ram.0.1_RDATA_2 ;
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:22.13-22.18" *)
  (* unused_bits = "0 1 2 4 5 6 7 8 9 10 12 13 14 15" *)
  wire [15:0] \ram.0.2_RDATA ;
  (* force_downto = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \ram.0.2_RDATA_1 ;
  (* force_downto = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \ram.0.2_RDATA_2 ;
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:22.13-22.18" *)
  (* unused_bits = "0 1 2 4 5 6 7 8 9 10 12 13 14 15" *)
  wire [15:0] \ram.0.3_RDATA ;
  (* force_downto = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \ram.0.3_RDATA_1 ;
  (* force_downto = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \ram.0.3_RDATA_2 ;
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:22.13-22.18" *)
  (* unused_bits = "0 1 2 4 5 6 7 8 9 10 12 13 14 15" *)
  wire [15:0] \ram.0.4_RDATA ;
  (* force_downto = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \ram.0.4_RDATA_1 ;
  (* force_downto = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \ram.0.4_RDATA_2 ;
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:22.13-22.18" *)
  (* unused_bits = "0 1 2 4 5 6 7 8 9 10 12 13 14 15" *)
  wire [15:0] \ram.0.5_RDATA ;
  (* force_downto = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \ram.0.5_RDATA_1 ;
  (* force_downto = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \ram.0.5_RDATA_2 ;
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:22.13-22.18" *)
  (* unused_bits = "0 1 2 4 5 6 7 8 9 10 12 13 14 15" *)
  wire [15:0] \ram.0.6_RDATA ;
  (* force_downto = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \ram.0.6_RDATA_1 ;
  (* force_downto = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \ram.0.6_RDATA_2 ;
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:22.13-22.18" *)
  (* unused_bits = "0 1 2 4 5 6 7 8 9 10 12 13 14 15" *)
  wire [15:0] \ram.0.7_RDATA ;
  (* force_downto = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \ram.0.7_RDATA_1 ;
  (* force_downto = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \ram.0.7_RDATA_2 ;
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:22.13-22.18" *)
  (* unused_bits = "0 1 2 4 5 6 7 8 9 10 12 13 14 15" *)
  wire [15:0] \ram.0.8_RDATA ;
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:22.13-22.18" *)
  (* unused_bits = "0 1 2 4 5 6 7 8 9 10 12 13 14 15" *)
  wire [15:0] \ram.0.9_RDATA ;
  (* force_downto = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \ram.1.0_RDATA ;
  (* force_downto = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \ram.1.0_RDATA_1 ;
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:22.13-22.18" *)
  (* unused_bits = "0 1 2 4 5 6 7 8 9 10 12 13 14 15" *)
  wire [15:0] \ram.1.0_RDATA_2 ;
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:22.13-22.18" *)
  (* unused_bits = "0 1 2 4 5 6 7 8 9 10 12 13 14 15" *)
  wire [15:0] \ram.1.10_RDATA ;
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:22.13-22.18" *)
  (* unused_bits = "0 1 2 4 5 6 7 8 9 10 12 13 14 15" *)
  wire [15:0] \ram.1.11_RDATA ;
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:22.13-22.18" *)
  (* unused_bits = "0 1 2 4 5 6 7 8 9 10 12 13 14 15" *)
  wire [15:0] \ram.1.12_RDATA ;
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:22.13-22.18" *)
  (* unused_bits = "0 1 2 4 5 6 7 8 9 10 12 13 14 15" *)
  wire [15:0] \ram.1.13_RDATA ;
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:22.13-22.18" *)
  (* unused_bits = "0 1 2 4 5 6 7 8 9 10 12 13 14 15" *)
  wire [15:0] \ram.1.14_RDATA ;
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:22.13-22.18" *)
  (* unused_bits = "0 1 2 4 5 6 7 8 9 10 12 13 14 15" *)
  wire [15:0] \ram.1.15_RDATA ;
  (* force_downto = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \ram.1.1_RDATA ;
  (* force_downto = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \ram.1.1_RDATA_1 ;
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:22.13-22.18" *)
  (* unused_bits = "0 1 2 4 5 6 7 8 9 10 12 13 14 15" *)
  wire [15:0] \ram.1.1_RDATA_2 ;
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:22.13-22.18" *)
  (* unused_bits = "0 1 2 4 5 6 7 8 9 10 12 13 14 15" *)
  wire [15:0] \ram.1.2_RDATA ;
  (* force_downto = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \ram.1.2_RDATA_1 ;
  (* force_downto = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \ram.1.2_RDATA_2 ;
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:22.13-22.18" *)
  (* unused_bits = "0 1 2 4 5 6 7 8 9 10 12 13 14 15" *)
  wire [15:0] \ram.1.3_RDATA ;
  (* force_downto = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \ram.1.3_RDATA_1 ;
  (* force_downto = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \ram.1.3_RDATA_2 ;
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:22.13-22.18" *)
  (* unused_bits = "0 1 2 4 5 6 7 8 9 10 12 13 14 15" *)
  wire [15:0] \ram.1.4_RDATA ;
  (* force_downto = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \ram.1.4_RDATA_1 ;
  (* force_downto = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \ram.1.4_RDATA_2 ;
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:22.13-22.18" *)
  (* unused_bits = "0 1 2 4 5 6 7 8 9 10 12 13 14 15" *)
  wire [15:0] \ram.1.5_RDATA ;
  (* force_downto = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \ram.1.5_RDATA_1 ;
  (* force_downto = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \ram.1.5_RDATA_2 ;
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:22.13-22.18" *)
  (* unused_bits = "0 1 2 4 5 6 7 8 9 10 12 13 14 15" *)
  wire [15:0] \ram.1.6_RDATA ;
  (* force_downto = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \ram.1.6_RDATA_1 ;
  (* force_downto = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \ram.1.6_RDATA_2 ;
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:22.13-22.18" *)
  (* unused_bits = "0 1 2 4 5 6 7 8 9 10 12 13 14 15" *)
  wire [15:0] \ram.1.7_RDATA ;
  (* force_downto = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \ram.1.7_RDATA_1 ;
  (* force_downto = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" *)
  wire [2:0] \ram.1.7_RDATA_2 ;
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:22.13-22.18" *)
  (* unused_bits = "0 1 2 4 5 6 7 8 9 10 12 13 14 15" *)
  wire [15:0] \ram.1.8_RDATA ;
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:22.13-22.18" *)
  (* unused_bits = "0 1 2 4 5 6 7 8 9 10 12 13 14 15" *)
  wire [15:0] \ram.1.9_RDATA ;
  (* src = "dpram.v:19.13-19.17" *)
  input re_b;
  wire re_b;
  (* src = "dpram.v:15.30-15.34" *)
  input we_a;
  wire we_a;
  wire we_a_SB_LUT4_I2_1_O;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) dat_a_out_SB_LUT4_O (
    .I0(1'h0),
    .I1(\ram.0.7_RDATA_1 [0]),
    .I2(\ram.0.7_RDATA_1 [1]),
    .I3(\ram.0.1_RDATA_1 [2]),
    .O(dat_a_out[15])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) dat_a_out_SB_LUT4_O_1 (
    .I0(1'h0),
    .I1(\ram.0.7_RDATA_2 [0]),
    .I2(\ram.0.7_RDATA_2 [1]),
    .I3(\ram.0.1_RDATA_1 [2]),
    .O(dat_a_out[14])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) dat_a_out_SB_LUT4_O_10 (
    .I0(1'h0),
    .I1(\ram.0.2_RDATA_1 [0]),
    .I2(\ram.0.2_RDATA_1 [1]),
    .I3(\ram.0.1_RDATA_1 [2]),
    .O(dat_a_out[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) dat_a_out_SB_LUT4_O_11 (
    .I0(1'h0),
    .I1(\ram.0.2_RDATA_2 [0]),
    .I2(\ram.0.2_RDATA_2 [1]),
    .I3(\ram.0.1_RDATA_1 [2]),
    .O(dat_a_out[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) dat_a_out_SB_LUT4_O_12 (
    .I0(1'h0),
    .I1(\ram.0.1_RDATA [0]),
    .I2(\ram.0.1_RDATA [1]),
    .I3(\ram.0.1_RDATA_1 [2]),
    .O(dat_a_out[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) dat_a_out_SB_LUT4_O_13 (
    .I0(1'h0),
    .I1(\ram.0.1_RDATA_1 [0]),
    .I2(\ram.0.1_RDATA_1 [1]),
    .I3(\ram.0.1_RDATA_1 [2]),
    .O(dat_a_out[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) dat_a_out_SB_LUT4_O_14 (
    .I0(1'h0),
    .I1(\ram.0.0_RDATA [0]),
    .I2(\ram.0.0_RDATA [1]),
    .I3(\ram.0.1_RDATA_1 [2]),
    .O(dat_a_out[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hccf0)
  ) dat_a_out_SB_LUT4_O_15 (
    .I0(1'h0),
    .I1(\ram.0.0_RDATA_1 [0]),
    .I2(\ram.0.0_RDATA_1 [1]),
    .I3(\ram.0.1_RDATA_1 [2]),
    .O(dat_a_out[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) dat_a_out_SB_LUT4_O_2 (
    .I0(1'h0),
    .I1(\ram.0.6_RDATA_1 [0]),
    .I2(\ram.0.6_RDATA_1 [1]),
    .I3(\ram.0.1_RDATA_1 [2]),
    .O(dat_a_out[13])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) dat_a_out_SB_LUT4_O_3 (
    .I0(1'h0),
    .I1(\ram.0.6_RDATA_2 [0]),
    .I2(\ram.0.6_RDATA_2 [1]),
    .I3(\ram.0.1_RDATA_1 [2]),
    .O(dat_a_out[12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) dat_a_out_SB_LUT4_O_4 (
    .I0(1'h0),
    .I1(\ram.0.5_RDATA_1 [0]),
    .I2(\ram.0.5_RDATA_1 [1]),
    .I3(\ram.0.1_RDATA_1 [2]),
    .O(dat_a_out[11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) dat_a_out_SB_LUT4_O_5 (
    .I0(1'h0),
    .I1(\ram.0.5_RDATA_2 [0]),
    .I2(\ram.0.5_RDATA_2 [1]),
    .I3(\ram.0.1_RDATA_1 [2]),
    .O(dat_a_out[10])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) dat_a_out_SB_LUT4_O_6 (
    .I0(1'h0),
    .I1(\ram.0.4_RDATA_1 [0]),
    .I2(\ram.0.4_RDATA_1 [1]),
    .I3(\ram.0.1_RDATA_1 [2]),
    .O(dat_a_out[9])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) dat_a_out_SB_LUT4_O_7 (
    .I0(1'h0),
    .I1(\ram.0.4_RDATA_2 [0]),
    .I2(\ram.0.4_RDATA_2 [1]),
    .I3(\ram.0.1_RDATA_1 [2]),
    .O(dat_a_out[8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) dat_a_out_SB_LUT4_O_8 (
    .I0(1'h0),
    .I1(\ram.0.3_RDATA_1 [0]),
    .I2(\ram.0.3_RDATA_1 [1]),
    .I3(\ram.0.1_RDATA_1 [2]),
    .O(dat_a_out[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) dat_a_out_SB_LUT4_O_9 (
    .I0(1'h0),
    .I1(\ram.0.3_RDATA_2 [0]),
    .I2(\ram.0.3_RDATA_2 [1]),
    .I3(\ram.0.1_RDATA_1 [2]),
    .O(dat_a_out[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) dat_b_SB_LUT4_O (
    .I0(1'h0),
    .I1(\ram.1.7_RDATA_1 [0]),
    .I2(\ram.1.7_RDATA_1 [1]),
    .I3(\ram.1.4_RDATA_2 [2]),
    .O(dat_b[15])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) dat_b_SB_LUT4_O_1 (
    .I0(1'h0),
    .I1(\ram.1.7_RDATA_2 [0]),
    .I2(\ram.1.7_RDATA_2 [1]),
    .I3(\ram.1.4_RDATA_2 [2]),
    .O(dat_b[14])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) dat_b_SB_LUT4_O_10 (
    .I0(1'h0),
    .I1(\ram.1.2_RDATA_1 [0]),
    .I2(\ram.1.2_RDATA_1 [1]),
    .I3(\ram.1.4_RDATA_2 [2]),
    .O(dat_b[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) dat_b_SB_LUT4_O_11 (
    .I0(1'h0),
    .I1(\ram.1.2_RDATA_2 [0]),
    .I2(\ram.1.2_RDATA_2 [1]),
    .I3(\ram.1.4_RDATA_2 [2]),
    .O(dat_b[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) dat_b_SB_LUT4_O_12 (
    .I0(1'h0),
    .I1(\ram.1.1_RDATA [0]),
    .I2(\ram.1.1_RDATA [1]),
    .I3(\ram.1.4_RDATA_2 [2]),
    .O(dat_b[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) dat_b_SB_LUT4_O_13 (
    .I0(1'h0),
    .I1(\ram.1.1_RDATA_1 [0]),
    .I2(\ram.1.1_RDATA_1 [1]),
    .I3(\ram.1.4_RDATA_2 [2]),
    .O(dat_b[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) dat_b_SB_LUT4_O_14 (
    .I0(1'h0),
    .I1(\ram.1.0_RDATA [0]),
    .I2(\ram.1.0_RDATA [1]),
    .I3(\ram.1.4_RDATA_2 [2]),
    .O(dat_b[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hccf0)
  ) dat_b_SB_LUT4_O_15 (
    .I0(1'h0),
    .I1(\ram.1.0_RDATA_1 [0]),
    .I2(\ram.1.0_RDATA_1 [1]),
    .I3(\ram.1.4_RDATA_2 [2]),
    .O(dat_b[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) dat_b_SB_LUT4_O_2 (
    .I0(1'h0),
    .I1(\ram.1.6_RDATA_1 [0]),
    .I2(\ram.1.6_RDATA_1 [1]),
    .I3(\ram.1.4_RDATA_2 [2]),
    .O(dat_b[13])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) dat_b_SB_LUT4_O_3 (
    .I0(1'h0),
    .I1(\ram.1.6_RDATA_2 [0]),
    .I2(\ram.1.6_RDATA_2 [1]),
    .I3(\ram.1.4_RDATA_2 [2]),
    .O(dat_b[12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) dat_b_SB_LUT4_O_4 (
    .I0(1'h0),
    .I1(\ram.1.5_RDATA_1 [0]),
    .I2(\ram.1.5_RDATA_1 [1]),
    .I3(\ram.1.4_RDATA_2 [2]),
    .O(dat_b[11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) dat_b_SB_LUT4_O_5 (
    .I0(1'h0),
    .I1(\ram.1.5_RDATA_2 [0]),
    .I2(\ram.1.5_RDATA_2 [1]),
    .I3(\ram.1.4_RDATA_2 [2]),
    .O(dat_b[10])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) dat_b_SB_LUT4_O_6 (
    .I0(1'h0),
    .I1(\ram.1.4_RDATA_1 [0]),
    .I2(\ram.1.4_RDATA_1 [1]),
    .I3(\ram.1.4_RDATA_2 [2]),
    .O(dat_b[9])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) dat_b_SB_LUT4_O_7 (
    .I0(1'h0),
    .I1(\ram.1.4_RDATA_2 [0]),
    .I2(\ram.1.4_RDATA_2 [1]),
    .I3(\ram.1.4_RDATA_2 [2]),
    .O(dat_b[8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) dat_b_SB_LUT4_O_8 (
    .I0(1'h0),
    .I1(\ram.1.3_RDATA_1 [0]),
    .I2(\ram.1.3_RDATA_1 [1]),
    .I3(\ram.1.4_RDATA_2 [2]),
    .O(dat_b[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) dat_b_SB_LUT4_O_9 (
    .I0(1'h0),
    .I1(\ram.1.3_RDATA_2 [0]),
    .I2(\ram.1.3_RDATA_2 [1]),
    .I3(\ram.1.4_RDATA_2 [2]),
    .O(dat_b[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hc000)
  ) en_a_SB_LUT4_I1 (
    .I0(1'h0),
    .I1(en_a),
    .I2(we_a),
    .I3(adr_a[11]),
    .O(en_a_SB_LUT4_I1_O[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'hf000)
  ) en_b_SB_LUT4_I2 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(en_b),
    .I3(re_b),
    .O(en_b_SB_LUT4_I2_O)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:204.532-204.765" *)
  SB_RAM40_4K #(
    .INIT_0(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ba00f000e700f500fc00da),
    .INIT_1(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_2(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_3(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_4(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_5(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_6(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_7(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_8(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_9(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_A(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_B(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_C(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_D(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_E(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_F(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .READ_MODE(2'h3),
    .WRITE_MODE(2'h3)
  ) \ram.0.0  (
    .MASK(16'hxxxx),
    .RADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .RCLK(clk_a),
    .RCLKE(we_a_SB_LUT4_I2_1_O),
    .RDATA({ \ram.0.0_RDATA_2 [15:12], \ram.0.0_RDATA [0], \ram.0.0_RDATA_2 [10:4], \ram.0.0_RDATA_1 [1], \ram.0.0_RDATA_2 [2:0] }),
    .RE(1'h1),
    .WADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .WCLK(clk_a),
    .WCLKE(en_a_SB_LUT4_I1_O[0]),
    .WDATA({ 4'hx, dat_a[1], 7'hxx, dat_a[0], 3'hx }),
    .WE(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:204.532-204.765" *)
  SB_RAM40_4K #(
    .INIT_0(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00aa00000000000000000000),
    .INIT_1(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_2(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_3(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_4(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_5(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_6(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_7(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_8(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_9(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_A(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_B(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_C(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_D(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_E(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_F(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .READ_MODE(2'h3),
    .WRITE_MODE(2'h3)
  ) \ram.0.1  (
    .MASK(16'hxxxx),
    .RADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .RCLK(clk_a),
    .RCLKE(we_a_SB_LUT4_I2_1_O),
    .RDATA({ \ram.0.1_RDATA_2 [15:12], \ram.0.1_RDATA [0], \ram.0.1_RDATA_2 [10:4], \ram.0.1_RDATA_1 [0], \ram.0.1_RDATA_2 [2:0] }),
    .RE(1'h1),
    .WADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .WCLK(clk_a),
    .WCLKE(en_a_SB_LUT4_I1_O[0]),
    .WDATA({ 4'hx, dat_a[3], 7'hxx, dat_a[2], 3'hx }),
    .WE(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:204.532-204.765" *)
  SB_RAM40_4K #(
    .INIT_0(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_1(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_2(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_3(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_4(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_5(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_6(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_7(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_8(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_9(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_A(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_B(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_C(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_D(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_E(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00eb00ff00ff),
    .INIT_F(256'bx0000000x1111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111),
    .READ_MODE(2'h3),
    .WRITE_MODE(2'h3)
  ) \ram.0.10  (
    .MASK(16'hxxxx),
    .RADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .RCLK(clk_a),
    .RCLKE(we_a_SB_LUT4_I2_1_O),
    .RDATA({ \ram.0.10_RDATA [15:12], \ram.0.2_RDATA_1 [1], \ram.0.10_RDATA [10:4], \ram.0.2_RDATA_2 [1], \ram.0.10_RDATA [2:0] }),
    .RE(1'h1),
    .WADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .WCLK(clk_a),
    .WCLKE(en_a_SB_LUT4_I1_O[1]),
    .WDATA({ 4'hx, dat_a[5], 7'hxx, dat_a[4], 3'hx }),
    .WE(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:204.532-204.765" *)
  SB_RAM40_4K #(
    .INIT_0(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_1(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_2(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_3(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_4(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_5(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_6(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_7(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_8(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_9(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_A(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_B(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_C(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_D(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_E(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00eb00ff00ff),
    .INIT_F(256'bx0000000x1111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111),
    .READ_MODE(2'h3),
    .WRITE_MODE(2'h3)
  ) \ram.0.11  (
    .MASK(16'hxxxx),
    .RADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .RCLK(clk_a),
    .RCLKE(we_a_SB_LUT4_I2_1_O),
    .RDATA({ \ram.0.11_RDATA [15:12], \ram.0.3_RDATA_1 [1], \ram.0.11_RDATA [10:4], \ram.0.3_RDATA_2 [1], \ram.0.11_RDATA [2:0] }),
    .RE(1'h1),
    .WADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .WCLK(clk_a),
    .WCLKE(en_a_SB_LUT4_I1_O[1]),
    .WDATA({ 4'hx, dat_a[7], 7'hxx, dat_a[6], 3'hx }),
    .WE(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:204.532-204.765" *)
  SB_RAM40_4K #(
    .INIT_0(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_1(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_2(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_3(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_4(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_5(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_6(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_7(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_8(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_9(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_A(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_B(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_C(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_D(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_E(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff04fb00ff00ff),
    .INIT_F(256'bx0000000x1111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111),
    .READ_MODE(2'h3),
    .WRITE_MODE(2'h3)
  ) \ram.0.12  (
    .MASK(16'hxxxx),
    .RADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .RCLK(clk_a),
    .RCLKE(we_a_SB_LUT4_I2_1_O),
    .RDATA({ \ram.0.12_RDATA [15:12], \ram.0.4_RDATA_1 [1], \ram.0.12_RDATA [10:4], \ram.0.4_RDATA_2 [1], \ram.0.12_RDATA [2:0] }),
    .RE(1'h1),
    .WADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .WCLK(clk_a),
    .WCLKE(en_a_SB_LUT4_I1_O[1]),
    .WDATA({ 4'hx, dat_a[9], 7'hxx, dat_a[8], 3'hx }),
    .WE(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:204.532-204.765" *)
  SB_RAM40_4K #(
    .INIT_0(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_1(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_2(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_3(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_4(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_5(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_6(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_7(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_8(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_9(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_A(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_B(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_C(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_D(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_E(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00eb00ff00ff),
    .INIT_F(256'bx0000000x1111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111),
    .READ_MODE(2'h3),
    .WRITE_MODE(2'h3)
  ) \ram.0.13  (
    .MASK(16'hxxxx),
    .RADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .RCLK(clk_a),
    .RCLKE(we_a_SB_LUT4_I2_1_O),
    .RDATA({ \ram.0.13_RDATA [15:12], \ram.0.5_RDATA_1 [1], \ram.0.13_RDATA [10:4], \ram.0.5_RDATA_2 [1], \ram.0.13_RDATA [2:0] }),
    .RE(1'h1),
    .WADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .WCLK(clk_a),
    .WCLKE(en_a_SB_LUT4_I1_O[1]),
    .WDATA({ 4'hx, dat_a[11], 7'hxx, dat_a[10], 3'hx }),
    .WE(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:204.532-204.765" *)
  SB_RAM40_4K #(
    .INIT_0(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_1(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_2(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_3(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_4(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_5(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_6(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_7(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_8(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_9(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_A(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_B(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_C(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_D(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_E(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_F(256'bx0000000x1111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111),
    .READ_MODE(2'h3),
    .WRITE_MODE(2'h3)
  ) \ram.0.14  (
    .MASK(16'hxxxx),
    .RADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .RCLK(clk_a),
    .RCLKE(we_a_SB_LUT4_I2_1_O),
    .RDATA({ \ram.0.14_RDATA [15:12], \ram.0.6_RDATA_1 [1], \ram.0.14_RDATA [10:4], \ram.0.6_RDATA_2 [1], \ram.0.14_RDATA [2:0] }),
    .RE(1'h1),
    .WADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .WCLK(clk_a),
    .WCLKE(en_a_SB_LUT4_I1_O[1]),
    .WDATA({ 4'hx, dat_a[13], 7'hxx, dat_a[12], 3'hx }),
    .WE(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:204.532-204.765" *)
  SB_RAM40_4K #(
    .INIT_0(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_1(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_2(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_3(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_4(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_5(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_6(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_7(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_8(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_9(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_A(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_B(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_C(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_D(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_E(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00eb00ff00ff),
    .INIT_F(256'bx0000000x1111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111),
    .READ_MODE(2'h3),
    .WRITE_MODE(2'h3)
  ) \ram.0.15  (
    .MASK(16'hxxxx),
    .RADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .RCLK(clk_a),
    .RCLKE(we_a_SB_LUT4_I2_1_O),
    .RDATA({ \ram.0.15_RDATA [15:12], \ram.0.7_RDATA_1 [1], \ram.0.15_RDATA [10:4], \ram.0.7_RDATA_2 [1], \ram.0.15_RDATA [2:0] }),
    .RE(1'h1),
    .WADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .WCLK(clk_a),
    .WCLKE(en_a_SB_LUT4_I1_O[1]),
    .WDATA({ 4'hx, dat_a[15], 7'hxx, dat_a[14], 3'hx }),
    .WE(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE \ram.0.1_RDATA_1_SB_DFFE_Q  (
    .C(clk_a),
    .D(adr_a[11]),
    .E(we_a_SB_LUT4_I2_1_O),
    .Q(\ram.0.1_RDATA_1 [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:204.532-204.765" *)
  SB_RAM40_4K #(
    .INIT_0(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00aa00000000000000000000),
    .INIT_1(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_2(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_3(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_4(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_5(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_6(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_7(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_8(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_9(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_A(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_B(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_C(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_D(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_E(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_F(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .READ_MODE(2'h3),
    .WRITE_MODE(2'h3)
  ) \ram.0.2  (
    .MASK(16'hxxxx),
    .RADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .RCLK(clk_a),
    .RCLKE(we_a_SB_LUT4_I2_1_O),
    .RDATA({ \ram.0.2_RDATA [15:12], \ram.0.2_RDATA_1 [0], \ram.0.2_RDATA [10:4], \ram.0.2_RDATA_2 [0], \ram.0.2_RDATA [2:0] }),
    .RE(1'h1),
    .WADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .WCLK(clk_a),
    .WCLKE(en_a_SB_LUT4_I1_O[0]),
    .WDATA({ 4'hx, dat_a[5], 7'hxx, dat_a[4], 3'hx }),
    .WE(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:204.532-204.765" *)
  SB_RAM40_4K #(
    .INIT_0(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00aa00000000000000000000),
    .INIT_1(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_2(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_3(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_4(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_5(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_6(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_7(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_8(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_9(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_A(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_B(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_C(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_D(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_E(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_F(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .READ_MODE(2'h3),
    .WRITE_MODE(2'h3)
  ) \ram.0.3  (
    .MASK(16'hxxxx),
    .RADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .RCLK(clk_a),
    .RCLKE(we_a_SB_LUT4_I2_1_O),
    .RDATA({ \ram.0.3_RDATA [15:12], \ram.0.3_RDATA_1 [0], \ram.0.3_RDATA [10:4], \ram.0.3_RDATA_2 [0], \ram.0.3_RDATA [2:0] }),
    .RE(1'h1),
    .WADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .WCLK(clk_a),
    .WCLKE(en_a_SB_LUT4_I1_O[0]),
    .WDATA({ 4'hx, dat_a[7], 7'hxx, dat_a[6], 3'hx }),
    .WE(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:204.532-204.765" *)
  SB_RAM40_4K #(
    .INIT_0(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00aa31ab2918e53083a1486b),
    .INIT_1(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_2(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_3(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_4(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_5(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_6(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_7(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_8(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_9(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_A(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_B(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_C(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_D(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_E(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_F(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .READ_MODE(2'h3),
    .WRITE_MODE(2'h3)
  ) \ram.0.4  (
    .MASK(16'hxxxx),
    .RADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .RCLK(clk_a),
    .RCLKE(we_a_SB_LUT4_I2_1_O),
    .RDATA({ \ram.0.4_RDATA [15:12], \ram.0.4_RDATA_1 [0], \ram.0.4_RDATA [10:4], \ram.0.4_RDATA_2 [0], \ram.0.4_RDATA [2:0] }),
    .RE(1'h1),
    .WADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .WCLK(clk_a),
    .WCLKE(en_a_SB_LUT4_I1_O[0]),
    .WDATA({ 4'hx, dat_a[9], 7'hxx, dat_a[8], 3'hx }),
    .WE(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:204.532-204.765" *)
  SB_RAM40_4K #(
    .INIT_0(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff10ae0806a088413080e65349),
    .INIT_1(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_2(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_3(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_4(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_5(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_6(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_7(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_8(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_9(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_A(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_B(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_C(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_D(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_E(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_F(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .READ_MODE(2'h3),
    .WRITE_MODE(2'h3)
  ) \ram.0.5  (
    .MASK(16'hxxxx),
    .RADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .RCLK(clk_a),
    .RCLKE(we_a_SB_LUT4_I2_1_O),
    .RDATA({ \ram.0.5_RDATA [15:12], \ram.0.5_RDATA_1 [0], \ram.0.5_RDATA [10:4], \ram.0.5_RDATA_2 [0], \ram.0.5_RDATA [2:0] }),
    .RE(1'h1),
    .WADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .WCLK(clk_a),
    .WCLKE(en_a_SB_LUT4_I1_O[0]),
    .WDATA({ 4'hx, dat_a[11], 7'hxx, dat_a[10], 3'hx }),
    .WE(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:204.532-204.765" *)
  SB_RAM40_4K #(
    .INIT_0(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff01eb1f4638a0386680941210),
    .INIT_1(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_2(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_3(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_4(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_5(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_6(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_7(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_8(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_9(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_A(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_B(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_C(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_D(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_E(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_F(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .READ_MODE(2'h3),
    .WRITE_MODE(2'h3)
  ) \ram.0.6  (
    .MASK(16'hxxxx),
    .RADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .RCLK(clk_a),
    .RCLKE(we_a_SB_LUT4_I2_1_O),
    .RDATA({ \ram.0.6_RDATA [15:12], \ram.0.6_RDATA_1 [0], \ram.0.6_RDATA [10:4], \ram.0.6_RDATA_2 [0], \ram.0.6_RDATA [2:0] }),
    .RE(1'h1),
    .WADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .WCLK(clk_a),
    .WCLKE(en_a_SB_LUT4_I1_O[0]),
    .WDATA({ 4'hx, dat_a[13], 7'hxx, dat_a[12], 3'hx }),
    .WE(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:204.532-204.765" *)
  SB_RAM40_4K #(
    .INIT_0(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00aa4f496838000a00440011),
    .INIT_1(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_2(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_3(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_4(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_5(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_6(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_7(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_8(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_9(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_A(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_B(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_C(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_D(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_E(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_F(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .READ_MODE(2'h3),
    .WRITE_MODE(2'h3)
  ) \ram.0.7  (
    .MASK(16'hxxxx),
    .RADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .RCLK(clk_a),
    .RCLKE(we_a_SB_LUT4_I2_1_O),
    .RDATA({ \ram.0.7_RDATA [15:12], \ram.0.7_RDATA_1 [0], \ram.0.7_RDATA [10:4], \ram.0.7_RDATA_2 [0], \ram.0.7_RDATA [2:0] }),
    .RE(1'h1),
    .WADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .WCLK(clk_a),
    .WCLKE(en_a_SB_LUT4_I1_O[0]),
    .WDATA({ 4'hx, dat_a[15], 7'hxx, dat_a[14], 3'hx }),
    .WE(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:204.532-204.765" *)
  SB_RAM40_4K #(
    .INIT_0(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_1(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_2(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_3(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_4(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_5(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_6(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_7(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_8(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_9(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_A(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_B(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_C(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_D(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_E(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00eb00ff00ff),
    .INIT_F(256'bx0000000x1111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111),
    .READ_MODE(2'h3),
    .WRITE_MODE(2'h3)
  ) \ram.0.8  (
    .MASK(16'hxxxx),
    .RADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .RCLK(clk_a),
    .RCLKE(we_a_SB_LUT4_I2_1_O),
    .RDATA({ \ram.0.8_RDATA [15:12], \ram.0.0_RDATA [1], \ram.0.8_RDATA [10:4], \ram.0.0_RDATA_1 [0], \ram.0.8_RDATA [2:0] }),
    .RE(1'h1),
    .WADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .WCLK(clk_a),
    .WCLKE(en_a_SB_LUT4_I1_O[1]),
    .WDATA({ 4'hx, dat_a[1], 7'hxx, dat_a[0], 3'hx }),
    .WE(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:204.532-204.765" *)
  SB_RAM40_4K #(
    .INIT_0(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_1(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_2(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_3(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_4(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_5(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_6(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_7(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_8(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_9(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_A(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_B(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_C(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_D(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_E(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00eb00ff00ff),
    .INIT_F(256'bx0000000x1111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111),
    .READ_MODE(2'h3),
    .WRITE_MODE(2'h3)
  ) \ram.0.9  (
    .MASK(16'hxxxx),
    .RADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .RCLK(clk_a),
    .RCLKE(we_a_SB_LUT4_I2_1_O),
    .RDATA({ \ram.0.9_RDATA [15:12], \ram.0.1_RDATA [1], \ram.0.9_RDATA [10:4], \ram.0.1_RDATA_1 [1], \ram.0.9_RDATA [2:0] }),
    .RE(1'h1),
    .WADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .WCLK(clk_a),
    .WCLKE(en_a_SB_LUT4_I1_O[1]),
    .WDATA({ 4'hx, dat_a[3], 7'hxx, dat_a[2], 3'hx }),
    .WE(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:204.532-204.765" *)
  SB_RAM40_4K #(
    .INIT_0(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ba00f000e700f500fc00da),
    .INIT_1(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_2(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_3(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_4(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_5(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_6(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_7(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_8(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_9(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_A(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_B(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_C(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_D(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_E(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_F(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .READ_MODE(2'h3),
    .WRITE_MODE(2'h3)
  ) \ram.1.0  (
    .MASK(16'hxxxx),
    .RADDR({ adr_b[0], adr_b[1], adr_b[2], adr_b[10:3] }),
    .RCLK(clk_b),
    .RCLKE(en_b_SB_LUT4_I2_O),
    .RDATA({ \ram.1.0_RDATA_2 [15:12], \ram.1.0_RDATA [0], \ram.1.0_RDATA_2 [10:4], \ram.1.0_RDATA_1 [1], \ram.1.0_RDATA_2 [2:0] }),
    .RE(1'h1),
    .WADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .WCLK(clk_a),
    .WCLKE(en_a_SB_LUT4_I1_O[0]),
    .WDATA({ 4'hx, dat_a[1], 7'hxx, dat_a[0], 3'hx }),
    .WE(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:204.532-204.765" *)
  SB_RAM40_4K #(
    .INIT_0(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00aa00000000000000000000),
    .INIT_1(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_2(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_3(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_4(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_5(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_6(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_7(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_8(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_9(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_A(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_B(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_C(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_D(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_E(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_F(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .READ_MODE(2'h3),
    .WRITE_MODE(2'h3)
  ) \ram.1.1  (
    .MASK(16'hxxxx),
    .RADDR({ adr_b[0], adr_b[1], adr_b[2], adr_b[10:3] }),
    .RCLK(clk_b),
    .RCLKE(en_b_SB_LUT4_I2_O),
    .RDATA({ \ram.1.1_RDATA_2 [15:12], \ram.1.1_RDATA [0], \ram.1.1_RDATA_2 [10:4], \ram.1.1_RDATA_1 [0], \ram.1.1_RDATA_2 [2:0] }),
    .RE(1'h1),
    .WADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .WCLK(clk_a),
    .WCLKE(en_a_SB_LUT4_I1_O[0]),
    .WDATA({ 4'hx, dat_a[3], 7'hxx, dat_a[2], 3'hx }),
    .WE(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:204.532-204.765" *)
  SB_RAM40_4K #(
    .INIT_0(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_1(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_2(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_3(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_4(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_5(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_6(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_7(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_8(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_9(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_A(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_B(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_C(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_D(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_E(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00eb00ff00ff),
    .INIT_F(256'bx0000000x1111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111),
    .READ_MODE(2'h3),
    .WRITE_MODE(2'h3)
  ) \ram.1.10  (
    .MASK(16'hxxxx),
    .RADDR({ adr_b[0], adr_b[1], adr_b[2], adr_b[10:3] }),
    .RCLK(clk_b),
    .RCLKE(en_b_SB_LUT4_I2_O),
    .RDATA({ \ram.1.10_RDATA [15:12], \ram.1.2_RDATA_1 [1], \ram.1.10_RDATA [10:4], \ram.1.2_RDATA_2 [1], \ram.1.10_RDATA [2:0] }),
    .RE(1'h1),
    .WADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .WCLK(clk_a),
    .WCLKE(en_a_SB_LUT4_I1_O[1]),
    .WDATA({ 4'hx, dat_a[5], 7'hxx, dat_a[4], 3'hx }),
    .WE(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:204.532-204.765" *)
  SB_RAM40_4K #(
    .INIT_0(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_1(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_2(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_3(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_4(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_5(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_6(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_7(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_8(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_9(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_A(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_B(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_C(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_D(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_E(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00eb00ff00ff),
    .INIT_F(256'bx0000000x1111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111),
    .READ_MODE(2'h3),
    .WRITE_MODE(2'h3)
  ) \ram.1.11  (
    .MASK(16'hxxxx),
    .RADDR({ adr_b[0], adr_b[1], adr_b[2], adr_b[10:3] }),
    .RCLK(clk_b),
    .RCLKE(en_b_SB_LUT4_I2_O),
    .RDATA({ \ram.1.11_RDATA [15:12], \ram.1.3_RDATA_1 [1], \ram.1.11_RDATA [10:4], \ram.1.3_RDATA_2 [1], \ram.1.11_RDATA [2:0] }),
    .RE(1'h1),
    .WADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .WCLK(clk_a),
    .WCLKE(en_a_SB_LUT4_I1_O[1]),
    .WDATA({ 4'hx, dat_a[7], 7'hxx, dat_a[6], 3'hx }),
    .WE(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:204.532-204.765" *)
  SB_RAM40_4K #(
    .INIT_0(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_1(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_2(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_3(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_4(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_5(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_6(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_7(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_8(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_9(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_A(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_B(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_C(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_D(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_E(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff04fb00ff00ff),
    .INIT_F(256'bx0000000x1111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111),
    .READ_MODE(2'h3),
    .WRITE_MODE(2'h3)
  ) \ram.1.12  (
    .MASK(16'hxxxx),
    .RADDR({ adr_b[0], adr_b[1], adr_b[2], adr_b[10:3] }),
    .RCLK(clk_b),
    .RCLKE(en_b_SB_LUT4_I2_O),
    .RDATA({ \ram.1.12_RDATA [15:12], \ram.1.4_RDATA_1 [1], \ram.1.12_RDATA [10:4], \ram.1.4_RDATA_2 [1], \ram.1.12_RDATA [2:0] }),
    .RE(1'h1),
    .WADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .WCLK(clk_a),
    .WCLKE(en_a_SB_LUT4_I1_O[1]),
    .WDATA({ 4'hx, dat_a[9], 7'hxx, dat_a[8], 3'hx }),
    .WE(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:204.532-204.765" *)
  SB_RAM40_4K #(
    .INIT_0(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_1(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_2(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_3(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_4(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_5(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_6(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_7(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_8(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_9(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_A(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_B(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_C(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_D(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_E(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00eb00ff00ff),
    .INIT_F(256'bx0000000x1111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111),
    .READ_MODE(2'h3),
    .WRITE_MODE(2'h3)
  ) \ram.1.13  (
    .MASK(16'hxxxx),
    .RADDR({ adr_b[0], adr_b[1], adr_b[2], adr_b[10:3] }),
    .RCLK(clk_b),
    .RCLKE(en_b_SB_LUT4_I2_O),
    .RDATA({ \ram.1.13_RDATA [15:12], \ram.1.5_RDATA_1 [1], \ram.1.13_RDATA [10:4], \ram.1.5_RDATA_2 [1], \ram.1.13_RDATA [2:0] }),
    .RE(1'h1),
    .WADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .WCLK(clk_a),
    .WCLKE(en_a_SB_LUT4_I1_O[1]),
    .WDATA({ 4'hx, dat_a[11], 7'hxx, dat_a[10], 3'hx }),
    .WE(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:204.532-204.765" *)
  SB_RAM40_4K #(
    .INIT_0(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_1(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_2(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_3(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_4(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_5(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_6(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_7(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_8(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_9(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_A(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_B(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_C(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_D(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_E(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_F(256'bx0000000x1111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111),
    .READ_MODE(2'h3),
    .WRITE_MODE(2'h3)
  ) \ram.1.14  (
    .MASK(16'hxxxx),
    .RADDR({ adr_b[0], adr_b[1], adr_b[2], adr_b[10:3] }),
    .RCLK(clk_b),
    .RCLKE(en_b_SB_LUT4_I2_O),
    .RDATA({ \ram.1.14_RDATA [15:12], \ram.1.6_RDATA_1 [1], \ram.1.14_RDATA [10:4], \ram.1.6_RDATA_2 [1], \ram.1.14_RDATA [2:0] }),
    .RE(1'h1),
    .WADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .WCLK(clk_a),
    .WCLKE(en_a_SB_LUT4_I1_O[1]),
    .WDATA({ 4'hx, dat_a[13], 7'hxx, dat_a[12], 3'hx }),
    .WE(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:204.532-204.765" *)
  SB_RAM40_4K #(
    .INIT_0(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_1(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_2(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_3(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_4(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_5(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_6(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_7(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_8(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_9(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_A(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_B(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_C(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_D(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_E(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00eb00ff00ff),
    .INIT_F(256'bx0000000x1111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111),
    .READ_MODE(2'h3),
    .WRITE_MODE(2'h3)
  ) \ram.1.15  (
    .MASK(16'hxxxx),
    .RADDR({ adr_b[0], adr_b[1], adr_b[2], adr_b[10:3] }),
    .RCLK(clk_b),
    .RCLKE(en_b_SB_LUT4_I2_O),
    .RDATA({ \ram.1.15_RDATA [15:12], \ram.1.7_RDATA_1 [1], \ram.1.15_RDATA [10:4], \ram.1.7_RDATA_2 [1], \ram.1.15_RDATA [2:0] }),
    .RE(1'h1),
    .WADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .WCLK(clk_a),
    .WCLKE(en_a_SB_LUT4_I1_O[1]),
    .WDATA({ 4'hx, dat_a[15], 7'hxx, dat_a[14], 3'hx }),
    .WE(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:204.532-204.765" *)
  SB_RAM40_4K #(
    .INIT_0(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00aa00000000000000000000),
    .INIT_1(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_2(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_3(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_4(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_5(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_6(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_7(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_8(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_9(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_A(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_B(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_C(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_D(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_E(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_F(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .READ_MODE(2'h3),
    .WRITE_MODE(2'h3)
  ) \ram.1.2  (
    .MASK(16'hxxxx),
    .RADDR({ adr_b[0], adr_b[1], adr_b[2], adr_b[10:3] }),
    .RCLK(clk_b),
    .RCLKE(en_b_SB_LUT4_I2_O),
    .RDATA({ \ram.1.2_RDATA [15:12], \ram.1.2_RDATA_1 [0], \ram.1.2_RDATA [10:4], \ram.1.2_RDATA_2 [0], \ram.1.2_RDATA [2:0] }),
    .RE(1'h1),
    .WADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .WCLK(clk_a),
    .WCLKE(en_a_SB_LUT4_I1_O[0]),
    .WDATA({ 4'hx, dat_a[5], 7'hxx, dat_a[4], 3'hx }),
    .WE(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:204.532-204.765" *)
  SB_RAM40_4K #(
    .INIT_0(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00aa00000000000000000000),
    .INIT_1(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_2(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_3(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_4(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_5(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_6(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_7(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_8(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_9(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_A(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_B(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_C(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_D(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_E(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_F(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .READ_MODE(2'h3),
    .WRITE_MODE(2'h3)
  ) \ram.1.3  (
    .MASK(16'hxxxx),
    .RADDR({ adr_b[0], adr_b[1], adr_b[2], adr_b[10:3] }),
    .RCLK(clk_b),
    .RCLKE(en_b_SB_LUT4_I2_O),
    .RDATA({ \ram.1.3_RDATA [15:12], \ram.1.3_RDATA_1 [0], \ram.1.3_RDATA [10:4], \ram.1.3_RDATA_2 [0], \ram.1.3_RDATA [2:0] }),
    .RE(1'h1),
    .WADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .WCLK(clk_a),
    .WCLKE(en_a_SB_LUT4_I1_O[0]),
    .WDATA({ 4'hx, dat_a[7], 7'hxx, dat_a[6], 3'hx }),
    .WE(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:204.532-204.765" *)
  SB_RAM40_4K #(
    .INIT_0(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00aa31ab2918e53083a1486b),
    .INIT_1(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_2(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_3(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_4(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_5(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_6(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_7(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_8(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_9(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_A(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_B(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_C(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_D(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_E(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_F(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .READ_MODE(2'h3),
    .WRITE_MODE(2'h3)
  ) \ram.1.4  (
    .MASK(16'hxxxx),
    .RADDR({ adr_b[0], adr_b[1], adr_b[2], adr_b[10:3] }),
    .RCLK(clk_b),
    .RCLKE(en_b_SB_LUT4_I2_O),
    .RDATA({ \ram.1.4_RDATA [15:12], \ram.1.4_RDATA_1 [0], \ram.1.4_RDATA [10:4], \ram.1.4_RDATA_2 [0], \ram.1.4_RDATA [2:0] }),
    .RE(1'h1),
    .WADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .WCLK(clk_a),
    .WCLKE(en_a_SB_LUT4_I1_O[0]),
    .WDATA({ 4'hx, dat_a[9], 7'hxx, dat_a[8], 3'hx }),
    .WE(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/ff_map.v:5.57-5.103" *)
  SB_DFFE \ram.1.4_RDATA_2_SB_DFFE_Q  (
    .C(clk_b),
    .D(adr_b[11]),
    .E(en_b_SB_LUT4_I2_O),
    .Q(\ram.1.4_RDATA_2 [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:204.532-204.765" *)
  SB_RAM40_4K #(
    .INIT_0(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff10ae0806a088413080e65349),
    .INIT_1(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_2(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_3(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_4(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_5(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_6(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_7(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_8(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_9(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_A(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_B(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_C(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_D(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_E(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_F(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .READ_MODE(2'h3),
    .WRITE_MODE(2'h3)
  ) \ram.1.5  (
    .MASK(16'hxxxx),
    .RADDR({ adr_b[0], adr_b[1], adr_b[2], adr_b[10:3] }),
    .RCLK(clk_b),
    .RCLKE(en_b_SB_LUT4_I2_O),
    .RDATA({ \ram.1.5_RDATA [15:12], \ram.1.5_RDATA_1 [0], \ram.1.5_RDATA [10:4], \ram.1.5_RDATA_2 [0], \ram.1.5_RDATA [2:0] }),
    .RE(1'h1),
    .WADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .WCLK(clk_a),
    .WCLKE(en_a_SB_LUT4_I1_O[0]),
    .WDATA({ 4'hx, dat_a[11], 7'hxx, dat_a[10], 3'hx }),
    .WE(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:204.532-204.765" *)
  SB_RAM40_4K #(
    .INIT_0(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff01eb1f4638a0386680941210),
    .INIT_1(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_2(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_3(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_4(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_5(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_6(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_7(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_8(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_9(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_A(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_B(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_C(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_D(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_E(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_F(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .READ_MODE(2'h3),
    .WRITE_MODE(2'h3)
  ) \ram.1.6  (
    .MASK(16'hxxxx),
    .RADDR({ adr_b[0], adr_b[1], adr_b[2], adr_b[10:3] }),
    .RCLK(clk_b),
    .RCLKE(en_b_SB_LUT4_I2_O),
    .RDATA({ \ram.1.6_RDATA [15:12], \ram.1.6_RDATA_1 [0], \ram.1.6_RDATA [10:4], \ram.1.6_RDATA_2 [0], \ram.1.6_RDATA [2:0] }),
    .RE(1'h1),
    .WADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .WCLK(clk_a),
    .WCLKE(en_a_SB_LUT4_I1_O[0]),
    .WDATA({ 4'hx, dat_a[13], 7'hxx, dat_a[12], 3'hx }),
    .WE(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:204.532-204.765" *)
  SB_RAM40_4K #(
    .INIT_0(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00aa4f496838000a00440011),
    .INIT_1(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_2(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_3(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_4(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_5(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_6(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_7(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_8(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_9(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_A(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_B(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_C(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_D(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_E(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_F(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .READ_MODE(2'h3),
    .WRITE_MODE(2'h3)
  ) \ram.1.7  (
    .MASK(16'hxxxx),
    .RADDR({ adr_b[0], adr_b[1], adr_b[2], adr_b[10:3] }),
    .RCLK(clk_b),
    .RCLKE(en_b_SB_LUT4_I2_O),
    .RDATA({ \ram.1.7_RDATA [15:12], \ram.1.7_RDATA_1 [0], \ram.1.7_RDATA [10:4], \ram.1.7_RDATA_2 [0], \ram.1.7_RDATA [2:0] }),
    .RE(1'h1),
    .WADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .WCLK(clk_a),
    .WCLKE(en_a_SB_LUT4_I1_O[0]),
    .WDATA({ 4'hx, dat_a[15], 7'hxx, dat_a[14], 3'hx }),
    .WE(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:204.532-204.765" *)
  SB_RAM40_4K #(
    .INIT_0(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_1(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_2(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_3(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_4(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_5(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_6(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_7(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_8(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_9(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_A(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_B(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_C(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_D(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_E(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00eb00ff00ff),
    .INIT_F(256'bx0000000x1111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111),
    .READ_MODE(2'h3),
    .WRITE_MODE(2'h3)
  ) \ram.1.8  (
    .MASK(16'hxxxx),
    .RADDR({ adr_b[0], adr_b[1], adr_b[2], adr_b[10:3] }),
    .RCLK(clk_b),
    .RCLKE(en_b_SB_LUT4_I2_O),
    .RDATA({ \ram.1.8_RDATA [15:12], \ram.1.0_RDATA [1], \ram.1.8_RDATA [10:4], \ram.1.0_RDATA_1 [0], \ram.1.8_RDATA [2:0] }),
    .RE(1'h1),
    .WADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .WCLK(clk_a),
    .WCLKE(en_a_SB_LUT4_I1_O[1]),
    .WDATA({ 4'hx, dat_a[1], 7'hxx, dat_a[0], 3'hx }),
    .WE(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/brams_map.v:204.532-204.765" *)
  SB_RAM40_4K #(
    .INIT_0(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_1(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_2(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_3(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_4(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_5(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_6(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_7(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_8(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_9(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_A(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_B(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_C(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_D(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff),
    .INIT_E(256'h00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00ff00eb00ff00ff),
    .INIT_F(256'bx0000000x1111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111000000001111111100000000111111110000000011111111),
    .READ_MODE(2'h3),
    .WRITE_MODE(2'h3)
  ) \ram.1.9  (
    .MASK(16'hxxxx),
    .RADDR({ adr_b[0], adr_b[1], adr_b[2], adr_b[10:3] }),
    .RCLK(clk_b),
    .RCLKE(en_b_SB_LUT4_I2_O),
    .RDATA({ \ram.1.9_RDATA [15:12], \ram.1.1_RDATA [1], \ram.1.9_RDATA [10:4], \ram.1.1_RDATA_1 [1], \ram.1.9_RDATA [2:0] }),
    .RE(1'h1),
    .WADDR({ adr_a[0], adr_a[1], adr_a[2], adr_a[10:3] }),
    .WCLK(clk_a),
    .WCLKE(en_a_SB_LUT4_I1_O[1]),
    .WDATA({ 4'hx, dat_a[3], 7'hxx, dat_a[2], 3'hx }),
    .WE(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h3000)
  ) we_a_SB_LUT4_I2 (
    .I0(1'h0),
    .I1(adr_a[11]),
    .I2(we_a),
    .I3(en_a),
    .O(en_a_SB_LUT4_I1_O[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/leonardo/miniconda3/envs/digital/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0f00)
  ) we_a_SB_LUT4_I2_1 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(we_a),
    .I3(en_a),
    .O(we_a_SB_LUT4_I2_1_O)
  );
  assign \ram.1.3_RDATA_2 [2] = \ram.1.4_RDATA_2 [2];
  assign \ram.0.2_RDATA_2 [2] = \ram.0.1_RDATA_1 [2];
  assign \ram.0.7_RDATA_1 [2] = \ram.0.1_RDATA_1 [2];
  assign \ram.0.0_RDATA [2] = \ram.0.1_RDATA_1 [2];
  assign \ram.1.5_RDATA_1 [2] = \ram.1.4_RDATA_2 [2];
  assign \ram.0.1_RDATA [2] = \ram.0.1_RDATA_1 [2];
  assign \ram.1.5_RDATA_2 [2] = \ram.1.4_RDATA_2 [2];
  assign \ram.0.5_RDATA_1 [2] = \ram.0.1_RDATA_1 [2];
  assign \ram.1.3_RDATA_1 [2] = \ram.1.4_RDATA_2 [2];
  assign \ram.1.6_RDATA_2 [2] = \ram.1.4_RDATA_2 [2];
  assign \ram.1.4_RDATA_1 [2] = \ram.1.4_RDATA_2 [2];
  assign \ram.0.4_RDATA_2 [2] = \ram.0.1_RDATA_1 [2];
  assign \ram.1.2_RDATA_1 [2] = \ram.1.4_RDATA_2 [2];
  assign \ram.1.6_RDATA_1 [2] = \ram.1.4_RDATA_2 [2];
  assign \ram.1.2_RDATA_2 [2] = \ram.1.4_RDATA_2 [2];
  assign \ram.1.0_RDATA_1 [2] = \ram.1.4_RDATA_2 [2];
  assign \ram.0.4_RDATA_1 [2] = \ram.0.1_RDATA_1 [2];
  assign \ram.1.1_RDATA [2] = \ram.1.4_RDATA_2 [2];
  assign \ram.0.3_RDATA_2 [2] = \ram.0.1_RDATA_1 [2];
  assign \ram.1.0_RDATA [2] = \ram.1.4_RDATA_2 [2];
  assign \ram.1.7_RDATA_2 [2] = \ram.1.4_RDATA_2 [2];
  assign \ram.1.1_RDATA_1 [2] = \ram.1.4_RDATA_2 [2];
  assign \ram.0.0_RDATA_1 [2] = \ram.0.1_RDATA_1 [2];
  assign \ram.0.7_RDATA_2 [2] = \ram.0.1_RDATA_1 [2];
  assign \ram.0.3_RDATA_1 [2] = \ram.0.1_RDATA_1 [2];
  assign \ram.0.6_RDATA_1 [2] = \ram.0.1_RDATA_1 [2];
  assign \ram.0.2_RDATA_1 [2] = \ram.0.1_RDATA_1 [2];
  assign \ram.0.5_RDATA_2 [2] = \ram.0.1_RDATA_1 [2];
  assign \ram.1.7_RDATA_1 [2] = \ram.1.4_RDATA_2 [2];
  assign \ram.0.6_RDATA_2 [2] = \ram.0.1_RDATA_1 [2];
  assign { \ram.0.1_RDATA_2 [11], \ram.0.1_RDATA_2 [3] } = { \ram.0.1_RDATA [0], \ram.0.1_RDATA_1 [0] };
  assign { \ram.0.0_RDATA_2 [11], \ram.0.0_RDATA_2 [3] } = { \ram.0.0_RDATA [0], \ram.0.0_RDATA_1 [1] };
  assign { \ram.0.2_RDATA [11], \ram.0.2_RDATA [3] } = { \ram.0.2_RDATA_1 [0], \ram.0.2_RDATA_2 [0] };
  assign { \ram.0.3_RDATA [11], \ram.0.3_RDATA [3] } = { \ram.0.3_RDATA_1 [0], \ram.0.3_RDATA_2 [0] };
  assign { \ram.0.4_RDATA [11], \ram.0.4_RDATA [3] } = { \ram.0.4_RDATA_1 [0], \ram.0.4_RDATA_2 [0] };
  assign { \ram.1.0_RDATA_2 [11], \ram.1.0_RDATA_2 [3] } = { \ram.1.0_RDATA [0], \ram.1.0_RDATA_1 [1] };
  assign { \ram.1.1_RDATA_2 [11], \ram.1.1_RDATA_2 [3] } = { \ram.1.1_RDATA [0], \ram.1.1_RDATA_1 [0] };
  assign { \ram.1.2_RDATA [11], \ram.1.2_RDATA [3] } = { \ram.1.2_RDATA_1 [0], \ram.1.2_RDATA_2 [0] };
  assign { \ram.1.3_RDATA [11], \ram.1.3_RDATA [3] } = { \ram.1.3_RDATA_1 [0], \ram.1.3_RDATA_2 [0] };
  assign { \ram.1.4_RDATA [11], \ram.1.4_RDATA [3] } = { \ram.1.4_RDATA_1 [0], \ram.1.4_RDATA_2 [0] };
  assign { \ram.1.5_RDATA [11], \ram.1.5_RDATA [3] } = { \ram.1.5_RDATA_1 [0], \ram.1.5_RDATA_2 [0] };
  assign { \ram.1.6_RDATA [11], \ram.1.6_RDATA [3] } = { \ram.1.6_RDATA_1 [0], \ram.1.6_RDATA_2 [0] };
  assign { \ram.1.7_RDATA [11], \ram.1.7_RDATA [3] } = { \ram.1.7_RDATA_1 [0], \ram.1.7_RDATA_2 [0] };
  assign { \ram.1.8_RDATA [11], \ram.1.8_RDATA [3] } = { \ram.1.0_RDATA [1], \ram.1.0_RDATA_1 [0] };
  assign { \ram.1.9_RDATA [11], \ram.1.9_RDATA [3] } = { \ram.1.1_RDATA [1], \ram.1.1_RDATA_1 [1] };
  assign { \ram.1.10_RDATA [11], \ram.1.10_RDATA [3] } = { \ram.1.2_RDATA_1 [1], \ram.1.2_RDATA_2 [1] };
  assign { \ram.1.11_RDATA [11], \ram.1.11_RDATA [3] } = { \ram.1.3_RDATA_1 [1], \ram.1.3_RDATA_2 [1] };
  assign { \ram.1.12_RDATA [11], \ram.1.12_RDATA [3] } = { \ram.1.4_RDATA_1 [1], \ram.1.4_RDATA_2 [1] };
  assign { \ram.1.13_RDATA [11], \ram.1.13_RDATA [3] } = { \ram.1.5_RDATA_1 [1], \ram.1.5_RDATA_2 [1] };
  assign { \ram.1.14_RDATA [11], \ram.1.14_RDATA [3] } = { \ram.1.6_RDATA_1 [1], \ram.1.6_RDATA_2 [1] };
  assign { \ram.1.15_RDATA [11], \ram.1.15_RDATA [3] } = { \ram.1.7_RDATA_1 [1], \ram.1.7_RDATA_2 [1] };
  assign { \ram.0.5_RDATA [11], \ram.0.5_RDATA [3] } = { \ram.0.5_RDATA_1 [0], \ram.0.5_RDATA_2 [0] };
  assign { \ram.0.6_RDATA [11], \ram.0.6_RDATA [3] } = { \ram.0.6_RDATA_1 [0], \ram.0.6_RDATA_2 [0] };
  assign { \ram.0.7_RDATA [11], \ram.0.7_RDATA [3] } = { \ram.0.7_RDATA_1 [0], \ram.0.7_RDATA_2 [0] };
  assign { \ram.0.8_RDATA [11], \ram.0.8_RDATA [3] } = { \ram.0.0_RDATA [1], \ram.0.0_RDATA_1 [0] };
  assign { \ram.0.9_RDATA [11], \ram.0.9_RDATA [3] } = { \ram.0.1_RDATA [1], \ram.0.1_RDATA_1 [1] };
  assign { \ram.0.10_RDATA [11], \ram.0.10_RDATA [3] } = { \ram.0.2_RDATA_1 [1], \ram.0.2_RDATA_2 [1] };
  assign { \ram.0.11_RDATA [11], \ram.0.11_RDATA [3] } = { \ram.0.3_RDATA_1 [1], \ram.0.3_RDATA_2 [1] };
  assign { \ram.0.12_RDATA [11], \ram.0.12_RDATA [3] } = { \ram.0.4_RDATA_1 [1], \ram.0.4_RDATA_2 [1] };
  assign { \ram.0.13_RDATA [11], \ram.0.13_RDATA [3] } = { \ram.0.5_RDATA_1 [1], \ram.0.5_RDATA_2 [1] };
  assign { \ram.0.14_RDATA [11], \ram.0.14_RDATA [3] } = { \ram.0.6_RDATA_1 [1], \ram.0.6_RDATA_2 [1] };
  assign { \ram.0.15_RDATA [11], \ram.0.15_RDATA [3] } = { \ram.0.7_RDATA_1 [1], \ram.0.7_RDATA_2 [1] };
endmodule
